name: Build iOS

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter --version
      - run: flutter pub get

      - name: Install CocoaPods dependencies
        run: |
          cd ios
          pod install

      - name: Build unsigned IPA
        run: flutter build ipa --release --no-codesign

      - uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: build/ios/ipa/
